<script>
</script>

<template>
    <header>
        <div>
            <a href="#" arail-label="Arboles y Bananas,Inicio">
                <span aria-hidden="true">🐒</span>
                <span>Casas y Arboles</span>
                <span>Bananas y Uvas</span>
            </a>
            <nav>
                <ul>
                    <li>aca va a estar el nav</li>
                </ul>
            </nav>
        </div>
    </header>
</template>

<style>
</style>